// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAtD_LiEqzgM8sWQBgNFeMUDT-xTTklMw',
    appId: '1:646361906649:web:581ba1a3c0ce7f08dbadc8',
    messagingSenderId: '646361906649',
    projectId: 'fsmdashboard-1f0d5',
    authDomain: 'fsmdashboard-1f0d5.firebaseapp.com',
    databaseURL: 'https://fsmdashboard-1f0d5-default-rtdb.firebaseio.com',
    storageBucket: 'fsmdashboard-1f0d5.appspot.com',
    measurementId: 'G-3S47P44ZXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMC08aDrwVrJ1JUUE8uijl9ZnFtgY0KUA',
    appId: '1:646361906649:android:4ea022b0e74ba054dbadc8',
    messagingSenderId: '646361906649',
    projectId: 'fsmdashboard-1f0d5',
    databaseURL: 'https://fsmdashboard-1f0d5-default-rtdb.firebaseio.com',
    storageBucket: 'fsmdashboard-1f0d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJFE5PriAwsRKtI-Vhe_os5FQRRUNDLFI',
    appId: '1:646361906649:ios:c612b2bc411f065bdbadc8',
    messagingSenderId: '646361906649',
    projectId: 'fsmdashboard-1f0d5',
    databaseURL: 'https://fsmdashboard-1f0d5-default-rtdb.firebaseio.com',
    storageBucket: 'fsmdashboard-1f0d5.appspot.com',
    iosClientId: '646361906649-75k4105m81oabv6cu6h7dbo5q3p4ukh6.apps.googleusercontent.com',
    iosBundleId: 'com.fsm.mprc.mprc',
  );
}
